// new Number() = 인스턴스 생성
// Number() = 숫자값으로 변환하여 반환
// constructor = 생성자
// toString() = 숫자값을 문자열로 변환
// toLocaleString() = 숫자값을 지역화 문자로 변환
// valueOf() = 프리미티브값 반환
// toExponential() =  지수표기로 변환
// toFixed() = 고정 소숫점 표기로 변환
// toPrecision() = 고정 소숫점 또는 지수 표기로 변환
// to = 변환